import assert from 'node:assert/strict';
import { claimEligibility, taskScope, requireTaskOwner, proposalScopeError, prepareTaskWorkspace, requireIntegratedHead } from '../lib/runtime/parallel-tasks.js';
import { obligationFrontier } from '../lib/protocol/obligation.js';
import { boardWriteDenial } from '../lib/runtime/board-guard.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createDriverWorktrees, snapshotCandidate, integrateCandidate } from '../lib/runtime/worktrees.js';
import { taskWorkspace } from '../lib/runtime/workspace-context.js';
import { captureEvidenceBoundary, assertEvidenceBoundary } from '../lib/tools/verification-boundary.js';
import { workspaceFingerprint } from '../lib/tools/oracle-exec.js';
import { initialProtocolState } from '../lib/protocol/machine.js';
import { createTeamDir, writeTeam, readTeam } from '../lib/state/store.js';
import { registerTaskTools } from '../lib/tools/task.js';
import { registerFlowTools } from '../lib/tools/flow.js';
import { registerOracleTools } from '../lib/tools/oracle.js';
import { gateStateFingerprint } from '../lib/protocol/gate.js';
const exec = promisify(execFile);
const git = async (cwd, ...args) => (await exec('git', args, { cwd, encoding: 'utf8' })).stdout.trim();

export async function run(report) {
  const check = async (name, fn) => { try { await fn(); report(true, name); } catch (error) { report(false, `${name}: ${error.stack}`); } };
  const driver = { name: 'driver', id: 'a', role: 'driver', status: 'idle' };
  const driver2 = { name: 'driver2', id: 'b', role: 'driver', status: 'idle' };
  const scope = writes => taskScope({ write_paths: writes, read_paths: [], resources: [] });
  const task = (id, writes) => ({ id, status: 'pending', dependencies: [], scope: scope(writes), trivial: true });
  const team = { id: 'x', mode: 'light', captainSessionId: 'c', parallel: { slots: {} }, members: [driver, driver2, { name: 'navigator', id: 'n', role: 'navigator' }], tasks: [task('t-1', ['a.js']), task('t-2', ['b.js'])], protocol: { phase: 'CYCLING', cycles: [], risks: [], arbitrations: [] } };
  await check('parallel independent ready tasks reserve distinct Drivers', () => {
    assert.deepEqual(obligationFrontier(team).filter(o => o.tool === 'pair_task_claim').map(o => [o.who, o.taskId]), [['driver', 't-1'], ['driver2', 't-2']]);
  });
  await check('scope conflicts and missing declarations serialize', () => {
    const live = { ...team.tasks[0], status: 'claimed', assignee: 'driver', attemptId: 'one' };
    const current = { ...team, tasks: [live, team.tasks[1]] };
    assert.equal(claimEligibility(current, driver2, current.tasks[1]), undefined);
    assert.match(claimEligibility(current, driver2, { ...task('t-3', ['a.js']) }), /scope/i);
    assert.match(claimEligibility(current, driver2, task('t-3', ['package-lock.json'])), /scope/i);
    assert.match(claimEligibility(current, driver2, task('t-3', ['src/types/contract.ts'])), /scope/i);
    assert.match(claimEligibility(current, driver2, { ...task('t-3', ['z.js']), scope: taskScope({}) }), /scope/i);
    assert.match(claimEligibility(current, driver2, { ...task('t-3', ['z.js']), scope: taskScope({ write_paths: ['z.js'], read_paths: ['a.js'], resources: [] }) }), /scope/i);
    assert.throws(() => taskScope({ write_paths: ['../escape'] }), /relative|workspace/i);
  });
  await check('parallel cycle ownership rejects sibling and old attempt', () => {
    const owned = { ...team.tasks[0], status: 'claimed', assignee: 'driver', attemptId: 'one' };
    const current = { ...team, tasks: [owned] };
    assert.equal(requireTaskOwner(current, owned, { id: 'a' }).name, 'driver');
    assert.throws(() => requireTaskOwner(current, owned, { id: 'b' }), /owner/i);
    assert.throws(() => requireTaskOwner(current, owned, { id: 'a' }, { owner: { memberId: 'a', assignee: 'driver', attemptId: 'old' } }), /attempt/i);
    assert.match(proposalScopeError(current, owned, ['b.js']), /scope/i);
    assert.match(proposalScopeError(current, owned, ['.pair-oracles/t-1/test.mjs']), /reserved/i);
    assert.equal(requireTaskOwner({ ...current, parallel: undefined }, owned, { id: 'b' }), undefined);
  });
  await check('isolated Driver editor refuses sibling, metadata and unknown targets', () => {
    const root = process.platform === 'win32' ? 'C:/pair/driver' : '/pair/driver';
    assert.match(boardWriteDenial(team, 'a', root, 'write', { path: 'a.js' }), /pair_task_claim/);
    assert.equal(boardWriteDenial(team, 'a', root, 'str_replace_editor', { command: 'view', path: root }), undefined, 'read-only editor view is not a write');
    const permitted = structuredClone(team);
    Object.assign(permitted.tasks[0], { assignee: 'driver', status: 'claimed', attemptId: 'current' });
    assert.match(boardWriteDenial(permitted, 'a', root, 'write', { path: 'a.js' }), /oracle|GO/);
    permitted.protocol.cycles.push({ taskId: 't-1', step: 'GO', owner: { memberId: 'a', attemptId: 'current' } });
    assert.equal(boardWriteDenial(permitted, 'a', root, 'write', { path: 'a.js' }), undefined);
    assert.match(boardWriteDenial(permitted, 'a', root, 'write', { path: 'b.js' }), /scope/);
    permitted.protocol.cycles[0].step = 'VERIFIED';
    assert.match(boardWriteDenial(permitted, 'a', root, 'write', { path: 'a.js' }), /GO/);
    assert.match(boardWriteDenial(team, 'a', root, 'write', { path: '../driver2/a.js' }), /isolated|workspace/i);
    assert.match(boardWriteDenial(team, 'a', root, 'write', { path: 'junction/../a.js' }), /traversal/);
    assert.match(boardWriteDenial(team, 'a', root, 'edit', { path: '.git/config' }), /reserved/i);
    assert.match(boardWriteDenial(team, 'a', root, 'apply_patch', { patch: 'unknown' }), /target/i);
    assert.match(boardWriteDenial(team, 'a', root, 'custom_write', { content: 'unknown' }), /target/i);
  });
  await check('accepted parallel task routes gate, integration and owner completion with stale fallback', () => {
    const current = structuredClone(team);
    current.tasks = [{ ...current.tasks[0], assignee: 'driver2', status: 'in_progress', attemptId: 'two' }];
    current.protocol.cycles = [{ id: 'c-1', taskId: 't-1', step: 'VERIFIED', verify: { verdict: 'accept' } }];
    assert.equal(obligationFrontier(current)[0].who, 'driver2');
    assert.equal(obligationFrontier(current)[0].tool, 'pair_gate_check');
    current.tasks[0].gatePassId = 'pass';
    current.protocol.gatePasses = [{ id: 'pass', taskId: 't-1', binding: { gateStateSha: gateStateFingerprint(current, 't-1'), worktreeSha: 'tree', taskAttempt: { attemptId: 'two', assignee: 'driver2' } } }];
    assert.equal(obligationFrontier(current)[0].tool, 'pair_integrate');
    current.parallel.integrations = { 't-1': { candidate: { gatePassId: 'pass', attemptId: 'two', worktreeSha: 'tree' } } };
    assert.equal(obligationFrontier(current)[0].tool, 'pair_task_update');
    current.tasks[0].description = 'changed';
    assert.equal(obligationFrontier(current)[0].tool, 'pair_gate_check');
    current.members.find(member => member.name === 'driver2').status = 'removed';
    assert.equal(obligationFrontier(current)[0].who, 'captain');
    assert.equal(obligationFrontier(current)[0].tool, 'pair_arbitrate');
  });
  await check('real Git candidate routing, boundaries, integration and slot preservation', async () => {
    const root = await mkdtemp(join(tmpdir(), 'pair-parallel-tasks-'));
    try {
      await git(root, 'init'); await git(root, 'config', 'user.name', 'Pair test'); await git(root, 'config', 'user.email', 'pair@test.invalid');
      await git(root, 'config', 'core.autocrlf', 'false');
      await writeFile(join(root, 'a.js'), 'old A\n'); await writeFile(join(root, 'b.js'), 'old B\n');
      await writeFile(join(root, '.gitignore'), 'cache/\nignored.txt\n');
      await git(root, 'add', '.'); await git(root, 'commit', '-m', 'base');
      const parallel = await createDriverWorktrees(root, join(root, '.pair-programming'), 'x');
      const current = { ...structuredClone(team), name: 'test', goal: 'g', tddMode: 'enforce', pairStyle: 'traditional', taskSeq: 2, createdAt: 1, updatedAt: 1, protocol: { ...initialProtocolState(), phase: 'CYCLING' }, parallel };
      for (const member of current.members) Object.assign(member, { joinedAt: 1, status: 'idle' });
      for (const card of current.tasks) Object.assign(card, { subject: card.id, createdAt: 1, updatedAt: 1 });
      const config = { stateDir: '.pair-programming' };
      const a = current.tasks[0], b = current.tasks[1];
      await prepareTaskWorkspace(current, driver, a, config);
      Object.assign(a, { assignee: driver.name, status: 'claimed', attemptId: 'one' });
      await prepareTaskWorkspace(current, driver2, b, config);
      Object.assign(b, { assignee: driver2.name, status: 'claimed', attemptId: 'two' });
      await createTeamDir(parallel.stateRoot, current);
      assert.notEqual(taskWorkspace(current, a.id, root), taskWorkspace(current, b.id, root));
      const defs = [];
      const ctx = { tools: { register: d => defs.push(d) }, logger: { warn() {}, debug() {} }, agents: { get() {} }, subagents: {} };
      const wakes = [];
      registerFlowTools(ctx, config, { scheduler: { async kickTeam(workspace, teamId) {
        const board = await readTeam(parallel.stateRoot, teamId);
        wakes.push({ workspace, task: board.tasks.find(t => t.id === a.id) });
      } } }); registerOracleTools(ctx, config);
      registerTaskTools(ctx, config, { scheduler: { async kickTeam() {} } });
      const call = (name, args, id) => defs.find(def => def.name === name).execute(args, { agent: { id, session: { header: { cwd: root }, append() {} } } });
      a.status = 'pending'; delete a.attemptId; delete a.workspace; delete a.baseHead;
      await writeTeam(parallel.stateRoot, current);
      const claimed = await call('pair_task_claim', { task_id: a.id }, 'a');
      assert.equal(wakes.length, 1, 'claim immediately wakes the newly owed Navigator');
      assert.equal(wakes[0].task.attemptId, claimed.attempt_id, 'ownership is durable before the wake');
      assert.equal(wakes[0].workspace, root);
      assert.deepEqual(claimed.write_paths, [join(claimed.workspace, 'a.js')]);
      assert.deepEqual(await call('pair_task_claim', { task_id: a.id }, 'a'), claimed, 'idempotent claims retain exact workspace targets');
      await call('pair_task_amend', { task_id: a.id, reason: 'Clarify before implementation', description: 'Clarified preparation' }, current.captainSessionId);
      const amended = (await readTeam(parallel.stateRoot, current.id)).tasks[0];
      assert.equal(amended.workspace, claimed.workspace);
      assert.equal(amended.assignee, 'driver');
      assert.equal(amended.status, 'pending');
      assert.equal(amended.attemptId, undefined);
      await writeFile(join(root, 'dependency.txt'), 'newly integrated dependency');
      await git(root, 'add', 'dependency.txt'); await git(root, 'commit', '-m', 'dependency arrived while preparing');
      const dependencyHead = await git(root, 'rev-parse', 'HEAD');
      const prepared = await readTeam(parallel.stateRoot, current.id);
      prepared.tasks.push({ id: 'dependency', subject: 'Integrated prerequisite', status: 'completed', dependencies: [], createdAt: 1, updatedAt: 1 });
      prepared.parallel.integrations ??= {};
      prepared.parallel.integrations.dependency = { head: dependencyHead };
      prepared.tasks[0].dependencies = ['dependency'];
      await writeTeam(parallel.stateRoot, prepared);
      const reclaimed = await call('pair_task_claim', { task_id: a.id }, 'a');
      assert.equal(reclaimed.base_head, dependencyHead);
      assert.equal(await readFile(join(reclaimed.workspace, 'dependency.txt'), 'utf8'), 'newly integrated dependency');
      assert.equal(reclaimed.workspace, claimed.workspace);
      assert.notEqual(reclaimed.attempt_id, claimed.attempt_id);
      a.status = 'claimed'; a.attemptId = 'one'; a.workspace = claimed.workspace; a.baseHead = reclaimed.base_head;
      parallel.slots.driver.baseHead = reclaimed.base_head;
      await writeTeam(parallel.stateRoot, current);
      // The artifact must PARSE: pair_oracle_write refuses a .mjs draft that cannot be
      // parsed (G1), because a broken artifact sealed as the standard can never go
      // green. A placeholder string was fine only while nothing checked it.
      await call('pair_oracle_write', { task_id: a.id, path: '.pair-oracles/t-1/test.mjs', content: 'console.log("A oracle");\n' }, 'n');
      await call('pair_oracle_write', { task_id: b.id, path: '.pair-oracles/t-2/test.mjs', content: 'console.log("B oracle");\n' }, 'n');
      assert.equal(await readFile(join(a.workspace, '.pair-oracles/t-1/test.mjs'), 'utf8'), 'console.log("A oracle");\n');
      await assert.rejects(readFile(join(b.workspace, '.pair-oracles/t-1/test.mjs')), /ENOENT/);
      await assert.rejects(call('pair_task_update', { task_id: a.id, attempt_id: 'one', status: 'in_progress' }, 'b'), /TASK_OWNER/);
      current.protocol.gatePasses.push({ id: 'pass', taskId: a.id, binding: {} }); a.gatePassId = 'pass'; a.status = 'in_progress';
      await writeTeam(parallel.stateRoot, current);
      await assert.rejects(call('pair_task_update', { task_id: a.id, attempt_id: 'one', gate_pass_id: 'pass', status: 'completed' }, 'a'), /INTEGRATION_REQUIRED/);
      const navigator = { id: 'n', session: { header: { cwd: root } } };
      const boundary = await captureEvidenceBoundary(current, a.id, navigator, config);
      assert.equal(boundary.workspace, a.workspace);
      await writeFile(join(b.workspace, 'b.js'), 'independent B\n'); current.protocol.phase = 'TASK_GATE';
      await assertEvidenceBoundary(boundary, current, navigator, config);
      await writeFile(join(a.workspace, 'a.js'), 'candidate A\n');
      await assert.rejects(assertEvidenceBoundary(boundary, current, navigator, config), /VERIFICATION_STALE/);
      await prepareTaskWorkspace(current, driver, a, config);
      assert.equal(a.attemptId, 'one'); assert.equal(await readFile(join(a.workspace, 'a.js'), 'utf8'), 'candidate A\n');
      const candidate = await snapshotCandidate(parallel.slots.driver, ['a.js', '.pair-oracles/t-1']);
      candidate.worktreeSha = await workspaceFingerprint(a.workspace, config);
      const merged = await integrateCandidate(parallel, candidate, { verify: async () => true });
      parallel.integrations = { [a.id]: { candidate, ...merged } }; a.status = 'completed';
      await requireIntegratedHead(current, a.id);
      assert.equal(taskWorkspace(current, a.id, root, { closure: true }), root);
      const next = task('t-3', ['a.js']); current.tasks.push(next);
      await writeFile(join(a.workspace, 'a.js'), 'unknown edit\n');
      await assert.rejects(prepareTaskWorkspace(current, driver, next, config), /unknown|unintegrated/);
      assert.equal(await readFile(join(a.workspace, 'a.js'), 'utf8'), 'unknown edit\n');
      await writeFile(join(a.workspace, 'a.js'), 'candidate A\n');
      await mkdir(join(a.workspace, 'cache')); await writeFile(join(a.workspace, 'cache/keep'), 'keep dependency cache');
      await writeFile(join(a.workspace, 'ignored.txt'), 'unknown ignored content');
      await writeFile(join(root, 'ignored.txt'), 'new tracked content'); await git(root, 'add', '-f', 'ignored.txt'); await git(root, 'commit', '-m', 'tracked collision');
      await assert.rejects(prepareTaskWorkspace(current, driver, next, config), /ignored artifacts overlap/);
      assert.equal(await readFile(join(a.workspace, 'ignored.txt'), 'utf8'), 'unknown ignored content');
      await rm(join(a.workspace, 'ignored.txt'));
      await prepareTaskWorkspace(current, driver, next, config);
      assert.equal(next.baseHead, await git(root, 'rev-parse', 'HEAD'));
      assert.equal(await readFile(join(a.workspace, 'cache/keep'), 'utf8'), 'keep dependency cache');
      await git(root, 'reset', '--hard', parallel.baseHead);
      await assert.rejects(requireIntegratedHead(current, a.id), /INTEGRATION_STALE/);
    } finally { await rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 }); }
  });
}
