import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
export function renderClient(readSource = file => readFileSync(new URL(file, root), 'utf8')) {
  const source = file => readSource(file).replace(/\r\n/g, '\n');
  const settings = source('lib/client/settings.js');
  const css = source('lib/client/panel.css');
  const panel = source('lib/client/panel.js').replace("/* PAIR_PANEL_CSS */ ''", JSON.stringify(css));
  const anchor = '    exports.apply = apply;';
  if (settings.split(anchor).length !== 2) throw new Error('client assembly anchor changed');
  return '/* Generated by scripts/build-client.mjs; edit lib/client/ sources. */\n' + settings.replace(anchor,
    panel + '\n    var settingsApply = apply;\n    apply = function (ctx) { settingsApply(ctx); installPairRuntimePanel(ctx, React); };\n' + anchor);
}
export function buildClient() { writeFileSync(new URL('lib/client.js', root), renderClient()); }
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) buildClient();
